name: Deploy THANN Model to Azure Web App

on:
  push:
    branches:
      - "main"  # Run workflow when changes are pushed to the main branch
  workflow_dispatch:  # Allow manual triggering of the workflow

env:
  AZURE_WEBAPP_NAME: "your-app-name"      # Replace with your Azure Web App name
  AZURE_WEBAPP_PACKAGE_PATH: "."          # Root directory where your model files are
  PYTHON_VERSION: "3.8"                   # Python version used for the app

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout Code
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Set up Python Environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      # Step 3: Install Dependencies
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run Unit Tests (Optional)
      - name: Run Tests
        run: |
          python -m unittest discover -s tests || echo "No tests found"

      # Step 5: Upload Build Artifact for Deployment
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: python-app
          path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

  deploy:
    runs-on: ubuntu-latest
    needs: build  # Only run deploy if the build step passes
    environment: 
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      # Step 1: Download Build Artifact
      - name: Download Build Artifact
        uses: actions/download-artifact@v3
        with:
          name: python-app
          path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

      # Step 2: Deploy to Azure Web App
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
